companies/urls.py
from django.urls import path
from .views import (
    home_view,
    create_company_view,
    delete_company_view,
    edit_company_view,
    use_company_view,
    calculate_stats_view,
)

app_name = 'companies'

urlpatterns = [
    path('', home_view, name='home'),
    path('companies/create/', create_company_view, name='create_company'),
    path('companies/delete/<pk>/', delete_company_view, name='delete_company'),
    path('companies/edit/<pk>/', edit_company_view, name='edit_company'),
    path('companies/use/<pk>/', use_company_view, name='use_company'),
    path('companies/calculate-stats/', calculate_stats_view, name='calculate_stats'),
]

members/urls.py
from django.urls import path
from .views import register_user_view, login_user_view, logout_user_view

app_name = 'members'

urlpatterns = [
    path('register-user/', register_user_view, name='register_user'),
    path('login/', login_user_view, name='login_user'),
    path('logout/', logout_user_view, name='logout_user'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls', namespace='companies')),
    path('', include('portfolios.urls', namespace='portfolios')),
]

portfolio_proj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls', namespace='companies')),
    path('portfolios/', include('portfolios.urls')),
    # path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

portfolios/urls.py
from django.urls import path
from .views import (
    calculate_portfolios_view,
    not_use_company_view,
    BoughtPortfolios,
    BoughtPortfolioDetail,
    create_bought_portfolio_view,
    delete_bought_portfolio_view,
)


app_name = 'portfolios'

urlpatterns = [
    path('', calculate_portfolios_view, name='create_portfolios'),
    path('not-use-company/<pk>/', not_use_company_view, name='not_use_company'),
    path('bought-portfolios/', BoughtPortfolios.as_view(), name='bought_portfolios'),
    path('bought-portfolios/<pk>/', BoughtPortfolioDetail.as_view(), name='bought_portfolio_info'),
    path('bought-portfolios/create-bought-portfolio/<pk>/', create_bought_portfolio_view, name='create_bought_portfolio'),
    path('bought-portfolios/delete/<pk>/', delete_bought_portfolio_view, name='delete_bought_portfolio'),
]

companies/models.py
from django.db import models
from django.contrib.auth.models import User
from math import sqrt

# Create your models here.


class Company(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    symbol = models.CharField(
        max_length=10,
    )
    name = models.CharField(max_length=100)

    USED_STATUS = [
        ('yes', 'used'),
        ('no', 'not used'),
    ]
    used_in_portfolio = models.CharField(
        max_length=3,
        choices=USED_STATUS,
        default='no',
    )

    def __str__(self):
        return str(self.symbol)

    class Meta:
        verbose_name_plural = "Companies"


class FinancialProfile(models.Model):
    company = models.OneToOneField(Company, on_delete=models.CASCADE)
    rate_of_return = models.FloatField(null=True, blank=True)
    volatility = models.FloatField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    def annual_rate_of_return(self):
        ann_ror = round(self.rate_of_return * 250, 2) if self.rate_of_return else None
        return ann_ror

    def annual_volatility(self):
        ann_vol = round(self.volatility * sqrt(250), 2) if self.volatility else None
        return ann_vol

    def __str__(self):
        return f'{self.company} - RoR: ({self.rate_of_return}) - Vol: ({self.volatility})'

companies/forms.py
from django import forms
from .models import Company
from datetime import date, timedelta

TODAY = date.today()
YEAR_AGO = date.today()-timedelta(days=365)


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ['symbol', 'name']


class CalculateStatsForm(forms.Form):
    date_from = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}),
                                initial=YEAR_AGO)
    date_to = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}),
                              initial=TODAY)

companies/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Company, FinancialProfile
from .utils_financial import company_df, df_mean_price, df_vol_price, corr_matrix
from .forms import CompanyForm, CalculateStatsForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


@login_required
def home_view(request):
    # Companies created by our user
    companies = Company.objects.filter(user=request.user).order_by(
        '-financialprofile__rate_of_return',
        'financialprofile__volatility',
    )
    create_company_form = CompanyForm()
    calculate_stats_form = CalculateStatsForm()
    edit_company_form = CompanyForm(initial={'symbol': Company.symbol,
    'name': Company.name})

    context = {
        'companies': companies,
        'create_company_form': create_company_form,
        'calculate_stats_form': calculate_stats_form,
        'edit_company_form': edit_company_form,
        'start_date': companies[0].financialprofile.start_date if companies else None,
        'end_date': companies[0].financialprofile.end_date if companies else None,
    }

    return render(request, 'companies/home.html', context=context)


@login_required
def create_company_view(request):
    companies = Company.objects.filter(user=request.user).order_by(
        '-financialprofile__rate_of_return',
        'financialprofile__volatility',
    )
    if request.method == 'POST':
        create_company_form = CompanyForm(request.POST)
        if create_company_form.is_valid():
            # Checking if our user already got company named like this
            existing_company = companies.filter(symbol=create_company_form.cleaned_data.get('symbol')).first()
            if existing_company:
                messages.error(request, 'Company already exists!')
            else:
                # Saving company with our user's id
                company = create_company_form.save(commit=False)
                company.user = request.user
                company.save()
                financialprofile = FinancialProfile(company=company)
                financialprofile.save()
                messages.success(request, 'Company added!')
            return redirect('companies:home')


@login_required
def delete_company_view(request, pk):
    # Deleting not wanted anymore companies in our user's db
    company_to_delete = get_object_or_404(Company, pk=pk)
    if company_to_delete.user == request.user:
        company_to_delete.delete()
        messages.info(request, 'Company deleted!')
        return redirect(reverse('companies:home'))
    else:
        messages.error(request, 'You cannot delete this company, because u ain\'t right user!')
        return redirect('companies:home')


@login_required
def edit_company_view(request, pk):
    # Editing company symbol or name
    company_to_edit = get_object_or_404(Company, pk=pk)
    if request.method == 'POST':
        edit_company_form = CompanyForm(request.POST or None,
                                        instance=company_to_edit)
        if edit_company_form.is_valid():
            edit_company_form.save()
            messages.info(request, 'Company updated!')
            return redirect('companies:home')


@login_required
def use_company_view(request, pk):
    # Changing status of companies (to be used in portfolio or not)
    company_to_use = get_object_or_404(Company, pk=pk)
    if request.method == 'POST':
        if company_to_use.used_in_portfolio == 'yes':
            company_to_use.used_in_portfolio = 'no'
        else:
            company_to_use.used_in_portfolio = 'yes'
        company_to_use.save()
        return redirect(reverse('companies:home')+'#use_companies_table')


@login_required
def calculate_stats_view(request):
    companies = Company.objects.filter(user=request.user).order_by(
        '-financialprofile__rate_of_return',
        'financialprofile__volatility',
    )
    if request.method == 'POST':
        calculate_stats_form = CalculateStatsForm(request.POST)
        if calculate_stats_form.is_valid():
            # We calculate our companies stats (rates and volatility) and create correlation matrix
            symbols = []
            date_from = calculate_stats_form.cleaned_data.get('date_from')
            date_to = calculate_stats_form.cleaned_data.get('date_to')
            for company in companies:
                # We use already existing loop to catch our symbols
                symbols.append(company.symbol)
                # Calculating rates and volatility for every company
                r_o_r = df_mean_price(
                    symbol=company.symbol,
                    date_from=date_from,
                    date_to=date_to,
                )
                vol = df_vol_price(
                    symbol=company.symbol,
                    date_from=date_from,
                    date_to=date_to,
                )
                # Updating company' profile with every calc
                FinancialProfile.objects.filter(company=company).update(
                    rate_of_return=r_o_r,
                    volatility=vol,
                    start_date=date_from,
                    end_date=date_to,
                )
            # Correlation matrix styles as table
            df = company_df(symbols, date_from=date_from, date_to=date_to)
            df_style = 'class="table table-striped table-dark table-hover"'
            corr_mat = corr_matrix(df, style=df_style)
            # Put it in session to do not need to create all the time new matrix
            request.session['corr_mat'] = corr_mat
            messages.success(request, 'Companies stats calculated!')
        return redirect('companies:home')

companies/templates/companies/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Companies
{% endblock title %}

{% block content %}
<div class="container text-center">
	<div class="container">
		<div class="row">
			<div class="col-6">
				<h3>Add company</h3>
				<form action="{% url 'companies:create_company' %}" method="POST" class="form-control bg-dark text-light">
					{% csrf_token %}
					{{ create_company_form|crispy }}
					<button type="submit" class="btn btn-primary">Save</button>
				</form>
			</div>
			<div class="col-6">
				<h3>Companies</h3>
				<table class="table table-dark table-striped">
					<tbody>
						{% for company in companies %}
						{% include 'companies/includes/modals.html' %}
						<tr>
							<td>{{ company.symbol }}</td>
							<td>{{ company.name }}</td>
							<td>
								<button type="button" class="btn btn-primary" data-bs-toggle="modal"
										data-bs-target="#Modal-CompanyEdit-{{ company.id }}">
								  Edit
								</button>
							</td>
							<td>
								<form action="{% url 'companies:delete_company' company.id %}" method="POST">{% csrf_token %}
									<input type="submit" class="btn btn-danger" value="Delete">
								</form>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
	
	<br/>
	<br/>
	
	<div class="container">
		<form action="{% url 'companies:calculate_stats' %}" method="POST" class="form-control bg-dark text-light">
			{% csrf_token %}
			{{ calculate_stats_form }}
			<button type="submit" class="btn btn-primary">Calculate</button>
		</form>
	</div>
	<br/>
	<br/>
	<h3>Companies Stats</h3>
	<h5>{{ companies.first.financialprofile.start_date|date:"d.m.Y" }} - {{ companies.first.financialprofile.end_date|date:"d.m.Y" }}</h5>
	<div class="container">
		<table class="table table-dark table-striped" id="use_companies_table">
			<thead>
				<tr>
					<td></td>
					<td>Symbol</td>
					<td>Name</td>
					<td>Rate of return (daily)</td>
					<td>Rate of return (annual)</td>
					<td>Volatility (daily)</td>
					<td>Volatility (annual)</td>
					<td></td>
				</tr>
			</thead>
			<tbody>
				{% for company in companies %}
				<tr>
					<td><b>{{ forloop.counter }}</b></td>
					<td>{{ company.symbol }}</td>
					<td>{{ company.name }}</td>
					<td>{{ company.financialprofile.rate_of_return }}%</td>
					<td>{{ company.financialprofile.annual_rate_of_return|floatformat }}%</td>
					<td>{{ company.financialprofile.volatility }}%</td>
					<td>{{ company.financialprofile.annual_volatility|floatformat }}%</td>
					<td>
						<form action="{% url 'companies:use_company' company.id %}" method="POST">{% csrf_token %}
							<input type="submit"
								{% if company.used_in_portfolio == 'yes' %}
									class="btn btn-danger"
									value="Not use in portfolio"
								{% else %}
									class="btn btn-success"
									value="Use in portfolio"
								{% endif %}>
						</form>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<a type="button" class="btn btn-primary"
			href="{% url 'portfolios:create_portfolios' %}">Create Portfolios</a>
	</div>
	<br/>
	{% if request.session.corr_mat %}
		<div class="container">
			<h3>Correlation</h3>
	<h5>{{ companies.first.financialprofile.start_date|date:"d.m.Y" }} - {{ companies.first.financialprofile.end_date|date:"d.m.Y" }}</h5>
			{{ request.session.corr_mat|safe }}
		</div>
	{% endif %}
</div>
{% endblock content %}