companies/urls.py
from django.urls import path
from .views import (
    home_view,
    create_company_view,
    delete_company_view,
    edit_company_view,
    use_company_view,
    calculate_stats_view,
)

app_name = 'companies'

urlpatterns = [
    path('', home_view, name='home'),
    path('companies/create/', create_company_view, name='create_company'),
    path('companies/delete/<pk>/', delete_company_view, name='delete_company'),
    path('companies/edit/<pk>/', edit_company_view, name='edit_company'),
    path('companies/use/<pk>/', use_company_view, name='use_company'),
    path('companies/calculate-stats/', calculate_stats_view, name='calculate_stats'),
]

members/urls.py
from django.urls import path
from .views import register_user_view, login_user_view, logout_user_view

app_name = 'members'

urlpatterns = [
    path('register-user/', register_user_view, name='register_user'),
    path('login/', login_user_view, name='login_user'),
    path('logout/', logout_user_view, name='logout_user'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls', namespace='companies')),
    path('', include('portfolios.urls', namespace='portfolios')),
]

portfolio_proj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls', namespace='companies')),
    path('portfolios/', include('portfolios.urls')),
    # path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

portfolios/urls.py
from django.urls import path
from .views import (
    calculate_portfolios_view,
    not_use_company_view,
    BoughtPortfolios,
    BoughtPortfolioDetail,
    create_bought_portfolio_view,
    delete_bought_portfolio_view,
)


app_name = 'portfolios'

urlpatterns = [
    path('', calculate_portfolios_view, name='create_portfolios'),
    path('not-use-company/<pk>/', not_use_company_view, name='not_use_company'),
    path('bought-portfolios/', BoughtPortfolios.as_view(), name='bought_portfolios'),
    path('bought-portfolios/<pk>/', BoughtPortfolioDetail.as_view(), name='bought_portfolio_info'),
    path('bought-portfolios/create-bought-portfolio/<pk>/', create_bought_portfolio_view, name='create_bought_portfolio'),
    path('bought-portfolios/delete/<pk>/', delete_bought_portfolio_view, name='delete_bought_portfolio'),
]

templates/includes/navbar.html
{% url 'companies:home' as home %}
{% url 'portfolios:create_portfolios' as portfolios %}
{% url 'portfolios:bought_portfolios' as bought_portfolios %}
{% url 'members:logout_user' as logout %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ home }}">Portfolio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarNav">
            <div>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ home }}">Companies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ portfolios }}">Portfolios</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ bought_portfolios }}">Bought Portfolios</a>
                    </li>
                </ul>
            </div>
            <div class="ms-auto">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link">{{ request.user.username }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ logout }}">Logout</a>
                    </li>
                    
                </ul>
            </div>
        </div>
        {% endif %}
    </div>
</nav>