companies/urls.py
from django.urls import path
from .views import (
    home_view,
    create_company_view,
    delete_company_view,
    edit_company_view,
    use_company_view,
    calculate_stats_view,
)

app_name = 'companies'

urlpatterns = [
    path('', home_view, name='home'),
    path('companies/create/', create_company_view, name='create_company'),
    path('companies/delete/<pk>/', delete_company_view, name='delete_company'),
    path('companies/edit/<pk>/', edit_company_view, name='edit_company'),
    path('companies/use/<pk>/', use_company_view, name='use_company'),
    path('companies/calculate-stats/', calculate_stats_view, name='calculate_stats'),
]

members/urls.py
from django.urls import path
from .views import register_user_view, login_user_view, logout_user_view

app_name = 'members'

urlpatterns = [
    path('register-user/', register_user_view, name='register_user'),
    path('login/', login_user_view, name='login_user'),
    path('logout/', logout_user_view, name='logout_user'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls', namespace='companies')),
    path('', include('portfolios.urls', namespace='portfolios')),
]

portfolio_proj/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('companies.urls', namespace='companies')),
    path('portfolios/', include('portfolios.urls')),
    # path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

portfolios/urls.py
from django.urls import path
from .views import (
    calculate_portfolios_view,
    not_use_company_view,
    BoughtPortfolios,
    BoughtPortfolioDetail,
    create_bought_portfolio_view,
    delete_bought_portfolio_view,
)


app_name = 'portfolios'

urlpatterns = [
    path('', calculate_portfolios_view, name='create_portfolios'),
    path('not-use-company/<pk>/', not_use_company_view, name='not_use_company'),
    path('bought-portfolios/', BoughtPortfolios.as_view(), name='bought_portfolios'),
    path('bought-portfolios/<pk>/', BoughtPortfolioDetail.as_view(), name='bought_portfolio_info'),
    path('bought-portfolios/create-bought-portfolio/<pk>/', create_bought_portfolio_view, name='create_bought_portfolio'),
    path('bought-portfolios/delete/<pk>/', delete_bought_portfolio_view, name='delete_bought_portfolio'),
]

portfolios/models.py
from django.db import models
from companies.models import Company
from django.contrib.auth.models import User
from django.shortcuts import reverse
from .utils_financial import get_actual_price


# Create your models here.

class CompanyWeight(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    company_weight = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f'{self.company} - {self.company_weight:.2f}%'


class Portfolio(models.Model):
    rate_of_return = models.FloatField(null=True, blank=True)
    volatility = models.FloatField(null=True, blank=True)
    PORTFOLIO_TYPES = [
        ('MVP', 'Minimal Volatility Portfolio'),
        ('ORP', 'Optimal Risky Portfolio'),
    ]
    portfolio_type = models.CharField(
        max_length=3,
        choices=PORTFOLIO_TYPES,
    )

    def __str__(self):
        if (self.rate_of_return != None) and (self.volatility != None):
            return f'Id: {self.id} RoR: {self.rate_of_return:.2f}% - Vol: {self.volatility:.2f}%'
        else:
            return f'Id: {self.id}'


class MVP(Portfolio):
    # Every user will have one MVP which will be updated when using prediction form
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_weights = models.ManyToManyField(CompanyWeight)


class ORP(Portfolio):
    # Every user will have one ORP which will be updated when using prediction form
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_weights = models.ManyToManyField(CompanyWeight)
    rf = models.FloatField(default=1)


class BoughtPortfolio(Portfolio):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    budget = models.FloatField()
    purchase_date = models.DateTimeField()

    def get_absolute_url(self):
        return reverse('portfolios:bought_portfolio_info', args=[str(self.id)])

    def purchase_whole_owned_capital(self):
        return sum([stocks.owned_capital for stocks in BoughtCompaniesStocks.objects.filter(bought_portfolio=self)])

    def now_whole_owned_capital(self):
        return sum([stocks.actual_price() * stocks.owned_stocks_amount for stocks in BoughtCompaniesStocks.objects.filter(bought_portfolio=self)])

    def summary_return(self):
        return sum([stocks.single_return() for stocks in BoughtCompaniesStocks.objects.filter(bought_portfolio=self)])


class BoughtCompaniesStocks(models.Model):
    # Not using foreign key, due to let user delete companies in home page (just saving symbol and name)
    symbol = models.CharField(
        max_length=10,
    )
    name = models.CharField(max_length=100)
    weight = models.FloatField()
    predicted_rate_of_return = models.FloatField()
    predicted_volatility = models.FloatField()
    purchase_price = models.FloatField()
    owned_stocks_amount = models.IntegerField()
    owned_capital = models.FloatField()
    date_of_purchase = models.DateField()
    bought_portfolio = models.ForeignKey(BoughtPortfolio, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.symbol} - {self.purchase_price} - {self.owned_stocks_amount} - {self.date_of_purchase}'

    def actual_price(self):
        actual_price = get_actual_price(self.symbol)['price']
        return actual_price

    def price_difference(self):
        return self.actual_price() - self.purchase_price

    def single_return(self):
        return (self.actual_price() * self.owned_stocks_amount) - self.owned_capital

    class Meta:
        verbose_name_plural = "Bought companies stocks"

portfolios/forms.py
from django import forms
from .models import BoughtPortfolio


class CalculatePortfoliosForm(forms.Form):
    rf = forms.FloatField(initial=1)


class BoughtPortfolioForm(forms.ModelForm):
    class Meta:
        model = BoughtPortfolio
        fields = ['budget']

portfolios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from companies.models import Company
from .forms import CalculatePortfoliosForm, BoughtPortfolioForm
from .models import MVP, ORP, BoughtPortfolio, CompanyWeight, BoughtCompaniesStocks, Portfolio
from .utils_financial import mvp_calculate, orp_calculate, get_actual_price, calculate_stocks_amount
from django.views.generic import ListView, DetailView
from django.contrib import messages
from datetime import datetime as dt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

@login_required
def calculate_portfolios_view(request):
    # We want just user companies to display and use them in MVP and ORP
    companies = Company.objects.filter(user=request.user).filter(used_in_portfolio='yes').order_by(
        'financialprofile__volatility',
        '-financialprofile__rate_of_return',
    )
    # We are looking for user's MVP and ORP (create them if are not in db)
    mvp, created = MVP.objects.get_or_create(
        user=request.user,
        defaults={'rate_of_return': None,
                  'volatility': None,
                  'portfolio_type': 'mvp',
                  'user': request.user,
                  }
    )
    orp, created = ORP.objects.get_or_create(
        user=request.user,
        defaults={'rate_of_return': None,
                  'volatility': None,
                  'portfolio_type': 'orp',
                  'user': request.user,
                  'rf': 0,
                  }
    )
    # Dates between we calculated our rates and volatility for our companies
    start_date = companies[0].financialprofile.start_date if companies else None
    end_date = companies[0].financialprofile.end_date if companies else None

    if request.method == 'POST':
        calculate_portfolios_form = CalculatePortfoliosForm(request.POST)
        invest_portfolio_form = BoughtPortfolioForm(request.POST)
        if calculate_portfolios_form.is_valid():
            rf = calculate_portfolios_form.cleaned_data.get('rf')
            # We are calculating MVP and ORP with our financial functions
            mvp_portfolio = mvp_calculate(
                companies=companies,
                start=start_date,
                end=end_date,
            )
            orp_portfolio = orp_calculate(
                companies=companies,
                start=start_date,
                end=end_date,
                rf=rf,
            )
            mvp, created = MVP.objects.update_or_create(
                user=request.user,
                defaults={'rate_of_return': mvp_portfolio['rate_of_return'],
                          'volatility': mvp_portfolio['volatility'],
                          'portfolio_type': 'mvp',
                          'user': request.user,
                          }
            )
            orp, created = ORP.objects.update_or_create(
                user=request.user,
                defaults={'rate_of_return': orp_portfolio['rate_of_return'],
                          'volatility': orp_portfolio['volatility'],
                          'portfolio_type': 'orp',
                          'user': request.user,
                          'rf': rf,
                          }
            )
            # Deleting previous company weights because we want to replace them with new ones
            mvp.company_weights.all().delete()
            orp.company_weights.all().delete()
            # Adding our companies weights to portfolios (many to many)
            for symbol, weight in mvp_portfolio['companies_weights'].items():
                company_weight = CompanyWeight(company=companies.get(symbol=symbol), company_weight=weight)
                company_weight.save()
                mvp.company_weights.add(company_weight)
            for symbol, weight in orp_portfolio['companies_weights'].items():
                company_weight = CompanyWeight(company=companies.get(symbol=symbol), company_weight=weight)
                company_weight.save()
                orp.company_weights.add(company_weight)
            messages.success(request, "MVP and ORP created!")
        return redirect('portfolios:create_portfolios')

    else:
        calculate_portfolios_form = CalculatePortfoliosForm()
        invest_portfolio_form = BoughtPortfolioForm()

    context = {
        'companies': companies,
        'calculate_portfolios_form': calculate_portfolios_form,
        'start_date':  start_date.strftime('%d.%m.%Y') if companies else None,
        'end_date':  end_date.strftime('%d.%m.%Y') if companies else None,
        'mvp': mvp,
        'orp': orp,
        'invest_portfolio_form': invest_portfolio_form,
    }

    return render(request, 'portfolios/portfolios.html', context=context)


@login_required
def not_use_company_view(request, pk):
    # Changing used company to not used and redirecting to same page
    company_to_use = get_object_or_404(Company, pk=pk)
    if request.method == 'POST':
        if company_to_use.used_in_portfolio == 'yes':
            company_to_use.used_in_portfolio = 'no'
            company_to_use.save()
    return redirect('portfolios:create_portfolios')


@login_required
def create_bought_portfolio_view(request, pk):
    portfolio = get_object_or_404(Portfolio, pk=pk)
    if portfolio.portfolio_type == 'mvp':
        portfolio = get_object_or_404(MVP, pk=pk)
    elif portfolio.portfolio_type == 'orp':
        portfolio = get_object_or_404(ORP, pk=pk)
    if request.method == 'POST':
        invest_portfolio_form = BoughtPortfolioForm(request.POST or None)
        if invest_portfolio_form.is_valid():
            budget = invest_portfolio_form.cleaned_data['budget']
            new_bought_portfolio = BoughtPortfolio.objects.create(
                user=request.user,
                budget=budget,
                purchase_date=dt.now(),
                rate_of_return=portfolio.rate_of_return,
                volatility=portfolio.volatility,
                portfolio_type=portfolio.portfolio_type.upper(),
            )
            new_bought_portfolio.save()
            for company_weight in portfolio.company_weights.all():
                actual_price = get_actual_price(company_weight.company.symbol)
                stocks_amount = calculate_stocks_amount(
                        budget=budget,
                        weight=company_weight.company_weight,
                        symbol=company_weight.company.symbol,
                    )
                stocks = BoughtCompaniesStocks(
                    symbol=company_weight.company.symbol,
                    name=company_weight.company.name,
                    weight=company_weight.company_weight,
                    predicted_rate_of_return=company_weight.company.financialprofile.rate_of_return,
                    predicted_volatility=company_weight.company.financialprofile.volatility,
                    purchase_price=actual_price['price'],
                    owned_stocks_amount=stocks_amount,
                    owned_capital=actual_price['price']*stocks_amount,
                    date_of_purchase=actual_price['date'],
                    bought_portfolio=new_bought_portfolio,
                )
                stocks.save()
    return redirect('portfolios:create_portfolios')


class BoughtPortfolios(LoginRequiredMixin, ListView):
    model = BoughtPortfolio
    template_name = 'portfolios/bought_portfolios.html'
    context_object_name = 'bought_portfolios'
    paginate_by = 6

    def get_queryset(self):
        return BoughtPortfolio.objects.filter(user=self.request.user).order_by(
                'purchase_date',
        )


class BoughtPortfolioDetail(LoginRequiredMixin, DetailView):
    model = BoughtPortfolio
    template_name = 'portfolios/bought_portfolio_detail.html'
    context_object_name = 'bought_portfolio'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        stocks = BoughtCompaniesStocks.objects.filter(bought_portfolio=self.object.id)
        context['all_stocks'] = stocks
        return context


@login_required
def delete_bought_portfolio_view(request, pk):
    # Deleting not wanted anymore portfolios in our user's db
    portfolio_to_delete = get_object_or_404(BoughtPortfolio, pk=pk)
    if portfolio_to_delete.user == request.user:
        portfolio_to_delete.delete()
        messages.info(request, 'Portfolio deleted!')
        return redirect('portfolios:bought_portfolios')
    else:
        messages.error(request, "You cannot delete this portfolio, because u ain't right user!")
        return redirect('portfolios:bought_portfolios')

portfolios/templates/portfolios/bought_portfolio_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}
Create Portfolios
{% endblock title %}


{% block content %}
<div class="container text-center">
	<h2>Portfolio details</h2>
	</br>
	<table class="table table-dark">
		<thead>
			<tr>
				<td colspan="4"><h4>Purchase Date: {{ bought_portfolio.purchase_date|date:"d.m.Y (H:i)" }} </h4></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Budget:</td>
				<td class="bg-light text-dark">{{ bought_portfolio.budget|floatformat:2 }} $</td>
				<td>Predicted rate of return:</td>
				<td class="bg-light text-dark">{{ bought_portfolio.rate_of_return|floatformat:2 }}%</td>
			</tr>
			<tr>
				<td>Type: </td>
				<td class="bg-light text-dark">{{ bought_portfolio.portfolio_type }}</td>
				<td>Predicted volatility:</td>
				<td class="bg-light text-dark">{{ bought_portfolio.volatility|floatformat:2 }}%</td>
			</tr>
		</tbody>
	</table>
	<table class="table table-dark align-middle">
		<thead>
			<tr>
				<td colspan="{{ all_stocks|length|add:'1' }}">
					<h5>Companies:</h5></td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Symbol:</td>
				{% for stocks in all_stocks %}
					<td>{{ stocks.symbol }}</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Name:</td>
				{% for stocks in all_stocks %}
					<td>{{ stocks.name }}</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Weights:</td>
				{% for stocks in all_stocks %}
					<td>{{ stocks.weight|floatformat:2 }}%</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Own stocks (amount):</td>
				{% for stocks in all_stocks %}
					<td>{{ stocks.owned_stocks_amount }}</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Purchased capital:</td>
				{% for stocks in all_stocks %}
					<td>{{ stocks.owned_capital|floatformat:2 }} $</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Purchase price:</td>
				{% for stocks in all_stocks %}
					<td>{{ stocks.purchase_price|floatformat:2 }} $</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Actual price:</td>
				{% for stocks in all_stocks %}
					<td class="{% if stocks.actual_price < stocks.purchase_price %} bg-danger {% else %} bg-success {% endif %}">
						{{ stocks.actual_price|floatformat:2 }} $</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Price difference:</td>
				{% for stocks in all_stocks %}
					<td class="{% if stocks.price_difference < 0 %} bg-danger {% else %} bg-success {% endif %}">
						{{ stocks.price_difference|floatformat:2 }} $</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Return:</td>
				{% for stocks in all_stocks %}
					<td class="{% if stocks.single_return < 0 %} bg-danger {% else %} bg-success {% endif %}">
						{{ stocks.single_return|floatformat:2 }} $</td>
				{% endfor %}
			</tr>
			<tr>
				<td>Owned capital in day of purchase:</td>
				<td colspan="{{ all_stocks|length }}">
					{{ bought_portfolio.purchase_whole_owned_capital|floatformat:2 }} $</td>
			</tr>
			<tr>
				<td>Summed capital now:</td>
				<td class="{% if bought_portfolio.now_whole_owned_capital < bought_portfolio.purchase_whole_owned_capital %} bg-danger {% else %} bg-success {% endif %}"
					colspan="{{ all_stocks|length }}">
					{{ bought_portfolio.now_whole_owned_capital|floatformat:2 }} $</td>
			</tr>
			<tr>
				
				<td><strong>Summed Return:</strong></td>
				<td class="{% if bought_portfolio.summary_return < 0 %} bg-danger {% else %} bg-success {% endif %}"
					colspan="{{ all_stocks|length }}">
					<strong>{{ bought_portfolio.summary_return|floatformat:2 }} $</strong></td>
			</tr>
		</tbody>
	</table>
</div>
{% endblock content %}

portfolios/templates/portfolios/bought_portfolios.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create Portfolios
{% endblock title %}


{% block content %}
<div class="container text-center">
	<h2>Bought Portfolios</h2>
	{% for portfolio in bought_portfolios %}
		<table class="table table-dark">
			<thead class="align-middle">
				<tr>
					<td class="bg-light text-dark"><h5>{{ forloop.counter }}</h5></td>
					<td>Purchase Date:</td>
					<td>Budget:</td>
					<td>Purchased capital:</td>
					<td>Actual value:</td>
					<td>Return:</td>
					<td colspan="2">Check:</td>
				</tr>
			</thead>
			<tbody>
				<tr class="align-middle">
					<td></td>
					<td>{{ portfolio.purchase_date|date:"d.m.Y (H:i)" }}</td>
					<td>{{ portfolio.budget|floatformat:2 }} $</td>
					<td>{{ portfolio.purchase_whole_owned_capital|floatformat:2 }} $</td>
					<td  class="{% if portfolio.summary_return < 0 %} bg-danger {% else %} bg-success {% endif %}">
						{{ portfolio.now_whole_owned_capital|floatformat:2 }} $</td>
					<td  class="{% if portfolio.summary_return < 0 %} bg-danger {% else %} bg-success {% endif %}">
						{{ portfolio.summary_return|floatformat:2 }} $</td>
					<td>
						<a href="{{ portfolio.get_absolute_url }}" class="btn btn-primary">Details</a>
					</td>
					<td>
						<form action="{% url 'portfolios:delete_bought_portfolio' portfolio.id %}" method="POST">{% csrf_token %}
							<input type="submit" class="btn btn-danger" value="Delete">
						</form>
					</td>
				</tr>
			</tbody>
		</table>
	{% endfor %}
</div>
{% endblock content %}

portfolios/templates/portfolios/portfolios.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Create Portfolios
{% endblock title %}


{% block content %}
<div class="container text-center">
	<h3>Companies in portfolios</h3>
	<h5>{{ start_date }} - {{ end_date }}</h5>
	<a type="button" class="btn btn-primary"
		href="{% url 'companies:home' %}#use_companies_table">Change</a>
	<br/>
	<br/>
	<table class="table table-dark table-striped">
		<thead>
			<tr>
				<td></td>
				<td>Symbol</td>
				<td>Name</td>
				<td>Rate of return (daily)</td>
				<td>Rate of return (annual)</td>
				<td>Volatility (daily)</td>
				<td>Volatility (annual)</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
			{% for company in companies %}
			<tr>
				<td><b>{{ forloop.counter }}</b></td>
				<td>{{ company.symbol }}</td>
				<td>{{ company.name }}</td>
				<td>{{ company.financialprofile.rate_of_return }}%</td>
				<td>{{ company.financialprofile.annual_rate_of_return }}%</td>
				<td>{{ company.financialprofile.volatility }}%</td>
				<td>{{ company.financialprofile.annual_volatility }}%</td>
				<td>
					<form action="{% url 'portfolios:not_use_company' company.id %}" method="POST">{% csrf_token %}
						<input type="submit"
								class="btn btn-danger"
								value="&#10006;">
					</form>
				</td>

			</tr>
			{% endfor %}
		</tbody>
	</table>
	<br/>

	<div class="container">
		{% if companies|length > 1 %}
			<form method="POST" class="form-control bg-dark text-light">
				{% csrf_token %}
				{{ calculate_portfolios_form }} %
				<button type="submit" class="btn btn-primary">Make predictions</button>
			</form>
		{% else %}
		<h3>You need at least 2 companies to make predictions!</h3>
		{% endif %}
	</div>
	<br/>
	<br/>
	<h3>Minimum Volatility Portfolio</h3>
	<h5>Calculated for dates: {{ start_date }} - {{ end_date }}</h5>
	<h5>Calculated for companies:
	 	{% for mvp_company in mvp.company_weights.all %}
			{{ mvp_company.company }}
		{% endfor %}
	</h5>
	<table class="table table-dark table-striped">
		<thead>
			<tr class="text-center align-middle">
				<td rowspan="2">Rate of return (annual)</td>
				<td rowspan="2">Volatility (annual)</td>
				<td colspan="{{ mvp.company_weights.all|length }}" class="text-center">
				Weights
				</td>
			</tr>
			<tr class="text-center align-middle">
				{% for mvp_company in mvp.company_weights.all %}
					<td>{{ mvp_company.company }} %</td>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ mvp.rate_of_return|floatformat:2 }}%</td>
				<td>{{ mvp.volatility|floatformat:2 }}%</td>
				{% for mvp_company in mvp.company_weights.all %}
					<td>{{ mvp_company.company_weight }} %</td>
				{% endfor %}
			</tr>
		</tbody>
	</table>
	{% include 'portfolios/includes/modals.html' %}
	<button type="button" class="btn btn-lg btn-primary" data-bs-toggle="modal"
										data-bs-target="#Modal-InvestMVPPortfolio-{{ mvp.id }}">
		  Invest in MVP
	</button>
	
	<br/>
	<br/>
	<br/>
	<h3>Optimal Risky Portfolio</h3>
	<h5>Calculated for dates: {{ start_date }} - {{ end_date }}</h5>
	<h5>Calculated for companies:
	 	{% for orp_company in orp.company_weights.all %}
			{{ orp_company.company }}
		{% endfor %}
	</h5>
	<h4>Rf = {{ orp.rf }}%</h4>
	<table class="table table-dark table-striped">
		<thead>
			<tr class="text-center align-middle">
				<td rowspan="2">Rate of return (annual)</td>
				<td rowspan="2">Volatility (annual)</td>
				<td colspan="{{ orp.company_weights.all|length }}" class="text-center">
				Weights
				</td>
			</tr>
			<tr class="text-center align-middle">
				{% for orp_company in orp.company_weights.all %}
					<td>{{ orp_company.company }} %</td>
				{% endfor %}
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ orp.rate_of_return|floatformat:2 }}%</td>
				<td>{{ orp.volatility|floatformat:2 }}%</td>
				{% for orp_company in orp.company_weights.all %}
					<td>{{ orp_company.company_weight }} %</td>
				{% endfor %}
			</tr>
		</tbody>
	</table>
	{% include 'portfolios/includes/modals.html' %}
	<button type="button" class="btn btn-lg btn-primary" data-bs-toggle="modal"
										data-bs-target="#Modal-InvestORPPortfolio-{{ orp.id }}">
		  Invest in ORP
	</button>
	<br/>
	<br/>
	<br/>
</div>
{% endblock content %}